import { categories, type Category, type Article, type ArticleSection } from "./content";

/* ═══════════════════════════════════════════════════════════
   i18n — Server-side internationalization helpers

   Supported locales: en (default), es, pt, zh
   Translations are cached JSON files generated by scripts/translate.mjs

   NOTE: This file uses Node.js crypto and is server-side only.
   For client-side, use i18n-shared.ts instead.
   ═══════════════════════════════════════════════════════════ */

// Re-export shared types/constants for server-side convenience
export { LOCALES, LOCALE_LABELS, LOCALE_FLAGS, isValidLocale } from "./i18n-shared";
export type { Locale } from "./i18n-shared";
import type { Locale } from "./i18n-shared";

// ── Translation cache ──

type TranslationCache = {
  _meta: { locale: string; updatedAt: string | null };
  strings: Record<string, { _src: string; text: string }>;
};

const translationCache = new Map<string, TranslationCache>();

function loadTranslations(locale: Locale): TranslationCache | null {
  if (locale === "en") return null;
  if (translationCache.has(locale)) return translationCache.get(locale)!;

  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const data = require(`./translations/${locale}.json`) as TranslationCache;
    translationCache.set(locale, data);
    return data;
  } catch {
    return null;
  }
}

function md5(text: string): string {
  // Server-side only hash using Node crypto
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const crypto = require("crypto");
  return crypto.createHash("md5").update(text).digest("hex").slice(0, 12);
}

function getTranslation(translations: TranslationCache | null, prefix: string, sourceText: string): string {
  if (!translations) return sourceText;
  const key = `${prefix}:${md5(sourceText)}`;
  const entry = translations.strings[key];
  return entry?.text || sourceText;
}

// ── Translate content ──

function translateSection(section: ArticleSection, t: TranslationCache | null): ArticleSection {
  return {
    heading: getTranslation(t, "heading", section.heading),
    body: getTranslation(t, "body", section.body),
  };
}

function translateArticle(article: Article, t: TranslationCache | null): Article {
  return {
    ...article,
    title: getTranslation(t, "title", article.title),
    summary: getTranslation(t, "summary", article.summary),
    sections: article.sections.map((s) => translateSection(s, t)),
  };
}

function translateCategory(category: Category, t: TranslationCache | null): Category {
  return {
    ...category,
    title: getTranslation(t, "title", category.title),
    description: getTranslation(t, "desc", category.description),
    articles: category.articles.map((a) => translateArticle(a, t)),
  };
}

// ── Public API (server-side only) ──

/**
 * Get all categories with translations applied for the given locale.
 * For "en", returns original content (no translation overhead).
 */
export function getLocalizedCategories(locale: Locale): Category[] {
  if (locale === "en") return categories;
  const t = loadTranslations(locale);
  return categories.map((c) => translateCategory(c, t));
}

/**
 * Get a single category by slug with translations.
 */
export function getLocalizedCategory(locale: Locale, slug: string): Category | undefined {
  const cats = getLocalizedCategories(locale);
  return cats.find((c) => c.slug === slug);
}

/**
 * Get a single article with translations.
 */
export function getLocalizedArticle(
  locale: Locale,
  categorySlug: string,
  articleSlug: string
): { category: Category; article: Article } | undefined {
  const category = getLocalizedCategory(locale, categorySlug);
  if (!category) return undefined;
  const article = category.articles.find((a) => a.slug === articleSlug);
  if (!article) return undefined;
  return { category, article };
}

/**
 * Get total article count (same for all locales).
 */
export function getTotalArticles(): number {
  return categories.reduce((sum, c) => sum + c.articles.length, 0);
}
